# -*- coding: utf-8 -*-
"""ai_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BF391A7i2OH4rCRth_6qjDOxPUDziV-

**Import diffusers for image generation**
"""

from diffusers import StableDiffusionPipeline

"""Mount a google drive"""

from google.colab import drive
drive.mount('/content/drive')

"""**AI Image model from hugging face**"""

image_model="runwayml/stable-diffusion-v1-5"

path="content/MyDrive/image_model"

"""**Download a model**"""

pipe=StableDiffusionPipeline.from_pretrained(image_model)
pipe.save_pretrained(path)

"""Prompt"""

image=pipe("A full Moon near in my house").images[0]
image.save("ai.png")

"""Display the image"""

from IPython.display import Image
Image("ai.png")

"""# Import transformers for text generation"""

from transformers import AutoModelForCausalLM, AutoTokenizer

"""**Download the code generate model**"""

tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-350M-mono")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-350M-mono")

"""Save the model"""

path="content//MyDrive/image_model"
model.save_pretrained(path)
tokenizer.save_pretrained(path)

"""**Prompt**"""

text = "write python code to find if the list contains duplicates"

"""Response"""

input_ids = tokenizer(text, return_tensors="pt").input_ids

generated_ids = model.generate(input_ids, max_length=128)
response=tokenizer.decode(generated_ids[0], skip_special_tokens=True)
print(response)